### ISSUE TITLE
Potential feature request: adding customized boundaries for SVI calculation

### ISSUE THREAD

**Issue by usamabilal** [cran/findSVI#1]
It just occurred to me that people may have customized boundaries where they want to calculate the SVI. An example would be the Philadelphia Neighborhoods computed by PHMC and used by the UHC in the health of the city report. These are nested in tracts (it means each neighborhood is cleanly composed of 2010 tracts) so it'd be easy to calculate the SVI at this level.

Two ways of going about this:

1. input boundaries
2. input a crosswalk

i'm tempted to say 2 makes more sense here, as it'd be easier to implement, and it'd accomodate ANY crosswalk that uses ANY defintiion at which the SVi can be calculated (e.g., groups of tracts, groups of ZCTAs, groups of counties, etc.).

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by usamabilal** [comment]
Thank you!
